name: docker
on: workflow_dispatch
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:current-alpine3.20
      env:
        API_URL: some-url.com
      ports:
        - 80
#      volumes:
#        - vol_name:/path/in/container
#        - /path/to/container
#        - /path/in/host:/path/in/container
    #options
    steps:
      - name: Log Node & OS  versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: creare a file
        run: echo 'some text' > somefile.txt
      - name: Container in a step
        uses: docker://node:current-alpine3.19
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      - name: show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: somefile.txt
    
