name: status
on: [push]


jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs of failure
        if: failure()
        run: echo "runs only on failure'
      - name: Runs on Success
        run: echo 'Runs on success'
      - name: always
        if: always()
        run: echo 'Always'
      - name: Runs when canceled
        if: cancelled()
        run: echo 'on cancel'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job 2'