name: vars and secrets
on: [ push ]
jobs:
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      JOB_LEVEL_VAR: ${{ vars.JOB_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}

    steps:
      - name: Run only if boolean secret is true
        if: secrets.BOOLEAN_SECRET == 'true'
        run: echo "i ran"
      - name: log vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "env: $ENV_LEVEL_VAR"
          echo "job: $JOB_LEVEL_VAR"
          echo "repo: $REPO_LEVEL_VAR"
          echo "org: $ORG_LEVEL_VAR"
